### ISSUE TITLE
allow functions to accept CompadreM class

### ISSUE THREAD

**Issue by wpetry** [jonesor/Rage#10]
Functions that currently require `matU`, `matF`, `...` arguments should also accept objects of class `CompadreM`, automatically parsing the matrix components or failing (with a helpful error) when a necessary component is missing.

Maybe best to write function generics with methods for the manual entry vs. com(p)adre database objects?

**Comment by tdjames1** [comment]
Yes, the idea was to overload the functions so that they can be used with separate matrix components (which don't necessarily have to originate from COMPADRE) or with the new CompadreM objects.

**Comment by jonesor** [comment]
This is now taken up with issue #112. Closing here.
