### ISSUE TITLE
Add unit tests for new functionality to support named life stages 

### ISSUE THREAD

**Issue by jonesor** [jonesor/Rage#101]
Add unit tests for the new functionality for `start` supporting named life stages (see #100)

**Comment by wpetry** [comment]
- [x] `life_expect`
- [ ] `net_repro_rate`
- [ ] life table functions in `mpm_to_.R`
- [ ] `qsd_converge`
- [ ] `longevity`
- [ ] functions in `mature_.R`
- [ ] `mpm_to_table`
- [ ] `checkValidStartLife` in `utils.R`

**Comment by wpetry** [comment]
Not sure why, but #103 failed to close this issue.
