### ISSUE TITLE
Rework 'Getting Started' vignette

### ISSUE THREAD

**Issue by wpetry** [jonesor/Rage#117]
Vision for this is to work as a baton pass/gateway from the basics of matrix population models to the functionality of `Rage`.

- opening paragraph recaps the basic anatomy of matrix models & the calculation of basic demographic statistics (e.g., lambda)
- general introduction to Rage functionality (+patterns for matrices for function input)
- 'switchboard' section that outlines the deeper dive vignettes so that readers know where to go next

This should be written such that the text _without_ paragraph 1 can stand alone as `Readme.md`.

**Comment by wpetry** [comment]
The section '1. Standardized vital rates' in #120 is my attempt at this vision. Happy to have feedback on scope/detail before moving on to the next sections.

**Comment by jonesor** [comment]
This is resolved (devel branch). Closing.
