### ISSUE TITLE
Add ability to use stage names in `exclude*` arguments

### ISSUE THREAD

**Issue by wpetry** [jonesor/Rage#121]
Add the ability to use stage names in `exclude`, `exclude_row`, and `exclude_col` arguments. Both of the following should work for a `matU` with named life stages:
```
vr_stasis(matU, exclude = 4)            # works
vr_stasis(matU, exclude = "dormant")    # fails
```

Relates to #93 and #111

**Comment by wpetry** [comment]
Detecting all functions with `exclude*` arguments with

```
tibble(fun = ls("package:Rage")) %>%
    mutate(args = map(fun, ~try(formalArgs(.x))),
           excl = map_lgl(.x = args, .f = ~any(str_detect(.x, "^exclude")))) %>%
    filter(excl)
```
Add support & update docs
- [ ] `perturb_trans`
   - `exclude_row`
   - `exclude_col`
- [ ] `vr_vec_growth`
   - `exclude`
   - `exclude_row`
   - `exclude_col`
- [ ] `vr_vec_reproduction`
   - `exclude_col`
- [ ] `vr_vec_shrinkage`
   - `exclude`
   - `exclude_row`
   - `exclude_col`
- [ ] `vr_vec_stasis`
   - `exclude`
- [ ] `vr_vec_survival`
   - `exclude_col`

Update docs only, calls corresponding `vr_vec_*` function
- [ ] `vr_fecundity`
- [ ] `vr_growth`
- [ ] `vr_shrinkage`
- [ ] `vr_stasis`
- [ ] `vr_survival`

**Comment by jonesor** [comment]
This is resolved (devel branch). Closing.
