### ISSUE TITLE
add helper function to name life stages

### ISSUE THREAD

**Issue by wpetry** [jonesor/Rage#122]
Would it be helpful to have a short function that names the life stages of matrices? The idea would be that the user would pass a matrix or list of matrices and a character vector with the corresponding life stage names.

```
nameStages <- function(mat, names) {
    # do some checks (all matrices are square, correct number of names supplied, ...)
    mat <- lapply(mat, function(x) `colnames<-`(x, names))
    mat <- lapply(mat, function(x) `rownames<-`(x, names))
    return(mat)
}
```

**Comment by jonesor** [comment]
Short answer, yes I think that would be useful.
It would be handy, I think, if it could default to some easy naming scheme like _A1, A2 ... An_.

In addition, at some point I would like to add a function to create `CompadreDB` and `CompadreMat` objects from user-supplied matrix lists, but that one should be in the `Rcompadre` package. Your proposed function would also be useful for that.

**Comment by wpetry** [comment]
What do y'all think about defaults for automatically-generated stage names? I'm thinking the name pattern would be {prefix}{delimiter}{number}. There are clear trade-offs between readability, length, and how well they would play with default sorting and other string processing functions. I'd appreciate any input.

**Prefix options**
- `A`: drawback is that folks could easily confuse stage names with the **A** matrix, especially when used as names for **U**/**F**/**C** matrices
- `s`: as in stage; nice that it's short
- `st`: as in stage
- `stg`: as in stage; longer but less ambiguous
- `cl`: as in class
- `stage`: totally unambiguous, but long
- `class`: totally unambiguous, but long; potential confusion with `class()` function in `R`

**Delimiter options**
- '': no character; keeps names short
- `_`: clear breaking character

**Number options**
- raw number: predictable
- left-padded number (e.g., if there are 9 stages, the numbers would be `1`...`9`; with 10 stages, `01`...`10`): less predictable, but sorts lexicographically

**Comment by jonesor** [comment]
I think that could be a nice idea for user-generated matrices. I agree that we should avoid ambiguity so I don't think we should use `A` as a prefix.
I think we should go favour unambiguity, and not worry about the length of the names, and use a clear breaking character.
Left padded numbers too.

So: `stage_01`, `stage_02` etc.

I don't think we have any matrices that exceed 99 stages, but "just in case" we should ensure that the padding takes care of that. e.g. something like this:

```
myStages <- 1:10
paste0("stage_",str_pad(myStages, max(nchar(myStages)), "left",pad = "0"))
```

**Comment by jonesor** [comment]
I think we should rename the function `name_stages` to make it style-consistent with the other functions. OK @wpetry?

**Comment by wpetry** [comment]
Yes, go ahead. I think I started work on this during the name style conversion & should have checked which case we were going to use. It looks like `vitalRates` is another camelCase function that should be converted to snake_case.

**Comment by jonesor** [comment]
Thanks for pointing out the same issue with `vitalRates` I'll fix that too.

**Comment by jonesor** [comment]
This is resolved (devel branch). Closing.
