### ISSUE TITLE
Split longevity function in two?

### ISSUE THREAD

**Issue by patrickbarks** [jonesor/Rage#13]
The `longevity` function returns two components:
* life expectancy and variance therein, estimated based on a Markov chain approach (from the fundamental matrix)
* maximum longevity, estimated via population projection (requires a initial population vector)

These two components seem sufficiently different to me that it might be worthwhile to split them into separate functions, or perhaps add an argument to the existing function to allow the user to select which component(s) to return.

Also, maximum longevity takes ~10x longer to calculate (on my computer: 5.5s vs 0.5s for the whole COMPADRE db), so it would be nice to exclude this extra computation time if the user only wants life expectancy.

**Comment by jonesor** [comment]
Yes - I agree. I guess the simplest approach is to add an argument to select components. (e.g. `method = "l0", "max", "both"`). Perhaps with the default being both, to retain backwards compatibility.

**Comment by patrickbarks** [comment]
Addressed by PR #17

**Comment by patrickbarks** [comment]
Can we revisit this @jonesor? We've broken backward compatibility in many other functions already (for good reason I believe), so I think we should split `longevity` into two separate functions: `longevity` and `lifeExpectancy`. Each will return a single value, making them very easy to document and program with. Plus, the function names will correspond exactly to what demographers would expect the functions to do.

**Comment by jonesor** [comment]
@patrickbarks - yes, I agree with this. Two clear and specific functions are preferable.
