### ISSUE TITLE
Finish adding stage name support

### ISSUE THREAD

**Issue by wpetry** [jonesor/Rage#142]
Matrices with named stages should be supported throughout the package. Support for this creeps in under a number of different function argument names, hence issues #93, #111, #121. This issue aims to complete stage name support by adding it for:

The `dorm_stages` argument in:
- [x] `vr_vec_dorm_enter`
- [x] `vr_vec_dorm_exit`
- [x] `vr_dorm_enter` (fix doc only)
- [x] `vr_dorm_exit` (fix doc only)

The `collapse` argument in:
- [x] `mpm_collapse`

The `repro_stages` argument in:
- [x] `mpm_standardize`
- [x]  `mpm_rearrange`

**Comment by wpetry** [comment]
It looks easy to add support for creating new names for collapsed stages in `mpm_collapse` by naming the elements of the `collapse` argument, so I'll go ahead and add that too.

**Comment by jonesor** [comment]
This is now fixed so closing this issue.
