### ISSUE TITLE
Specifying critical lx in longevity function

### ISSUE THREAD

**Issue by patrickbarks** [jonesor/Rage#16]
The maximum longevity component of `longevity` finds the age when survivorship (lx) falls to some critical proportion (call this `lx_crit`), which is 0.01 with the default setting of `initPop = 100`. Specifically, the population starts with `initPop` individuals in stage class `startLife`, and is projected through time until there is only 1 individual remaining (call this `n_crit`, which is fixed at 1).

I think it's potentially confusing that the user effectively adjusts `lx_crit` by changing `initPop` (i.e. `lx_crit = n_crit / initPop = 1 / initPop`).

As far as I can tell, the result depends only on the ratio, not the absolute values of `initPop` and `n_crit`. So I think it would be more intuitive if `initPop` was fixed at 1 and removed as an argument, and the user instead specified a new argument `lx_crit` (constrained to the interval [0,1], default = 0.01).

Alternatively, we could keep the function as is, and just improve the documentation.

(Also, related to #15 , I believe the loop within `longevity` is mathematically equivalent to the survivorship loop within `makeLifeTable`, `dEntropy`, and `kEntropy`, so some of this duplicated code could be pulled out into a common function.)

**Comment by jonesor** [comment]
Yes - It makes sennse to fix `initPop` as 1 as you suggest. Sometimes demographers like to use a different "Radix" (e.g. it is often 100,000 in human life tables), but if that is required it is trivial to mulitply it up in the output.

**Comment by patrickbarks** [comment]
I agree. Closed by #34
