### ISSUE TITLE
entropy_d is calculating the wrong formula

### ISSUE THREAD

**Issue by ellner** [jonesor/Rage#185]
Hello Rage-ers! In the course of our meta-analysis of luck using three databases, we discovered that entropy_d is calculating an incorrect formula for Demetrius's entropy of the lx*mx curve. What should happen is this: 

lxmx <- lx * mx
px <- lxmx/sum(lxmx); 
log_px <- log(px)
log_px[px == 0] <- 0
H <- -sum(px * log_px)

Send me an email if you want to discuss this. Thanks, 

Steve Ellner

**Comment by jonesor** [comment]
Thanks for spotting this Steve. Much appreciated! @wpetry has corrected the bug in the the github version of the package. I'll be sending an update through to CRAN within the next day or two.
