### ISSUE TITLE
Simplifying functions that can take matF, matC, or matF+matC

### ISSUE THREAD

**Issue by patrickbarks** [jonesor/Rage#19]
In `dEntropy`, `R0`, and `lifeTimeRepEvents` (and possibly `makeLifeTable`), I think the conditional structure of the output is overly complicated.

The user may pass:

1. `matF` only, or
2. `matC` only, or
3. `matF` and `matC`

and the number of items returned depends on which arguments get passed, as do the names of the returned list elements.

In my opinion this conditional behaviour is a pain to document, potentially difficult for new users to understand, and makes the functions harder to program with.

One option for simplification is to only have a single argument for the reproductive matrix (e.g. `matR`), to which the user can pass whatever they desire... i.e. one of `matF`, `matC`, or something like `matFC` (= `matF` + `matC`).

In this case, I think we would also need to make it easier for the user to derive `matFC` as a separate slot/colum within `db` (I think @levisc8's proposal in jonesor/Rcompadre#27 to merge the `mat` and `metadata` slots into a single `data` slot goes a long way here).

**Comment by jonesor** [comment]
I agree - it's a pain. I like your solution. Unless there are objections I say go ahead!

**Comment by jonesor** [comment]
Thanks for resolving this. 
I expect these changes will confuse some users so an updated vignette that we can use in training workshops should be a priority now.
