### ISSUE TITLE
Change package name to something more googleable

### ISSUE THREAD

**Issue by patrickbarks** [jonesor/Rage#21]
The Rcompadre repo is the first hit if you google "Rcompadre".

The Rage repo doesn't make page 1 with any of the following (of course search results are personalized, so may vary):
- "Rage"
- "Rage R"
- "Rage library"
- "Rage R package"
- "Rage GitHub" (!!!)

We'll eventually grow in popularity, but I don't think we'd ever be a top hit for just "Rage". I don't have any better ideas at the moment. Just throwing it out there.

**Comment by levisc8** [comment]
`ager`?

**Comment by patrickbarks** [comment]
It's certaintly much more googleable than Rage. I think a 4-character name would be hard to get to the top spot of Google unless it was quite unique (xkcd, mgcv, lme4), though top spot doesn't need to be our goal.

Here are some more thoughts on package naming from [rOpenSci](https://ropensci.github.io/dev_guide/building.html#package-name-and-metadata) and [Hadley Wickham](http://r-pkgs.had.co.nz/package.html).

**Comment by patrickbarks** [comment]
closing this, as the benefit of a better package name probably isn't worth the headache that a name change would entail at this point

**Comment by patrickbarks** [comment]
See also ["We shouldn't have called it 'Stan'"](https://statmodeling.stat.columbia.edu/2019/04/29/we-shouldntve-called-it-stan-i-shouldve-listened-to-bob-and-hadley/)
