### ISSUE TITLE
Remove standardizedVitalRates

### ISSUE THREAD

**Issue by patrickbarks** [jonesor/Rage#23]
`standardizedVitalRates` calls four other Rage functions in sequence: `rearrangeMatrix`, `reprodStages`, `collapseMatrix`, then `vitalRates`. The first 3 convert an MPM to a standardized format, and the 4th extracts averaged vital rates.

I see no reason to group these 4 components into a single function:
- The main reason is that each component function has it's own set of optional arguments (e.g. `reprodStages` has different options for dealing with propagule and post-reproductive stages, `vitalRates` has different options for how to split and weight vital rates). `standardizedVitalRates` doesn't currently support any of these — it simply uses the defaults of the component functions. Adding this support would make `standardizedVitalRates` overly complicated, in my opinion.

- Second, the four component functions may each fail for different reasons. Combining them in a single function makes debugging more difficult.

- Third, a user that wants to extract vital rates from a standardized matrix is likely to want to calculate other things from that standardized matrix as well. But the standardized matrix is not returned by `standardizedVitalRates`.

Therefore, I suggest we remove `standardizedVitalRates` and encourage users to use the four component functions separately (e.g. with an example on the website or vignette). We could alternatively bundle the first 3 component functions into a new function (e.g. `standardizeMatrix`), which I think would be more useful to users, and not quite as complicated.

**Comment by jonesor** [comment]
Looks good.
