### ISSUE TITLE
Use popbio to calculate lambda and ssd

### ISSUE THREAD

**Issue by patrickbarks** [jonesor/Rage#26]
Since we're already importing `popbio`, I suggest we consistently use `popbio::lambda` and `popbio::stable.stage` at relevant points within our functions, primarily for ease of code readability, and also for consistency. By my count, the relevant functions include:
- `collapseMatrix`
- `qsdConverge`
- `matrixElementPerturbation`
- `vitalRatePerturbation`
- `vitalRates`

**Comment by jonesor** [comment]
OK!
