### ISSUE TITLE
Modify R0 to always calculate per-generation growth rate

### ISSUE THREAD

**Issue by patrickbarks** [jonesor/Rage#27]
In _Matrix Population Models_, Caswell discusses methods for calculating R0 in age- vs. stage-classified models (s. 5.3.4). The continuous age-classified version (integral over lx * mx) gives the per-generation population growth rate, which corresponds qualitatively with lambda in terms of being < 1, = 1, or > 1.

To calculate R0 with the same properties from a stage-classified model, Caswell (p. 128) recommends the calculation:

```
R <- matF %*% N  # where N is the fundamental matrix
R0 <- popbio::lambda(R)  # i.e. dominant eigenvalue of R
```

whereas our current calculation is:

```
R <- matF %*% N
R0 <- R[startLife, startLife]
```

The two are the same if offspring only arise in stage `startLife`, but otherwise differ (only the former is affected by the production of offspring in any stage other than `startLife`).

I suggest we update R0 to use the eigenvalue method.

**Comment by RobSalGo** [comment]
I'd actually suggest to accommodate both ways to calculate it in this function

**Comment by patrickbarks** [comment]
What's the purpose of only looking at the expected production of a single type of offspring, if more than one type are produced?

I can see maybe looking at the expected lifetime production of _all_ offspring by simply summing across offspring types, as in

```
R <- matF %*% N
R0 <- sum(R[,startLife])
```

This would correspond to how we determine age-specific fertility in `makeLifeTable`, `dEntropy`, etc. (Though this doesn't seem like a great idea either, particularly if we are summing over both propagule and active stages).

**Comment by RobSalGo** [comment]
We'd be mixing apples and pears, and it may be in the interests of the researcher to produce those outputs separately - a lot of plant and marine demographers, for instance, don't consider the beginning of life until things get settled and germinate/attach... so black-boxing propagules with established individuals would be misleading to them...

**Comment by patrickbarks** [comment]
I'm not really advocating for the sum method. I just think the current method `R0 <- R[startLife, startLife]` is not general enough to warrant inclusion in Rage, because the result has no inherent meaning that is comparable among matrices (if there's more than one type of offspring).

Here's an example for Alliaria_petiolata_4 (mean matrix for population 'Ives Road'):

```
matU <- rbind(c(0.89,    0,   0),  # stage 1 is propagule
              c(0.04,    0,   0),
              c(   0, 0.05,   0))

matF <- rbind(c(   0,    0, 128),
              c(   0,    0,  18),
              c(   0,    0,   0))
```

lambda: 1.3
R0 (eigenvalue method): 3.2
R0 (current method, startLife = 2): 0.9

From the current method, the expected production of seedlings by an individual starting in the seedling stage seems to be below the replacement rate, even though the population is increasing, because the current method ignores the production of seeds that become seedlings a year or two later.

I imagine it's possible to calculate the expected lifetime production of 'seedling equivalents' — i.e. directly-produced seedlings + seeds that eventually become seedlings — this, I think, could be a useful quantity.

**Comment by jonesor** [comment]
I suppose there is still some discussion to be had about this @RobSalGo and @patrickbarks . 
I have already accepted Patrick's pull request so I am just making this note here to remind us that the current devel branch function now uses the eigen value method:

```
R <- matF %*% N  # where N is the fundamental matrix
R0 <- popbio::lambda(R)  # i.e. dominant eigenvalue of R
```

while the current master branch uses:

```
R <- matF %*% N
R0 <- R[startLife, startLife]
```

We can easily allow for users the flexibility to select the method with an argument in the function ...

**Comment by patrickbarks** [comment]
I suppose multiple options is the way to go. I'll add that back in my next PR. I suggest we also include a third option, which calculates the expected lifetime production of '_startLife_ equivalents' (summing across all offspring types weighted by reproductive value relative to the _startLife_ stage; from [Cochran and Ellner, 1992](https://doi.org/10.2307/2937115 )):

```
R <- matF %*% N  # where N is the fundamental matrix
v <- popbio::reproductive.value(matA)
v_scaled <- v / v[startLife]
R0 <- sum(R[, startLife] * v_scaled)
```

Caswell notes "there is no guarantee that such a sum will satisfy either of our desires for what R0 should do", but I've compared this method to the eigenvalue method for every MPM in COMPADRE, and, as long as `matA` is irreducible, the two methods correspond qualitatively (to each other and to &#955;). (There are 2 reducible/non-ergodic MPMs where the results don't correspond, because the _startLife_ stage is cut off from the reproductive stages.)

If offspring only arise in stage _startLife_, all 3 methods give the same result. If offspring arise in multiple stages, the results vary and each method is bad in its own way :)

#### method = 'generation'
- 'individual' in the units (i.e. individuals individual<sup>-1</sup> generation<sup>-1</sup>) refers to any and all stages

#### method = 'start.direct'
- ignores offspring that arise in any stage other than _startLife_

#### method = 'start.weighted'
- '_startLife_ equivalent' is a bit abstract
