### ISSUE TITLE
Make longevity and R0 return NA if matU is singular

### ISSUE THREAD

**Issue by patrickbarks** [jonesor/Rage#28]
Functions `longevity` (life expectancy component) and `R0` will fail if `matU` is singular (i.e. non-invertable). This usually indicates infinite life expectancy due to a 100% stasis loop in the final stage(s).

In jonesor/Rcompadre#30 I suggest adding a column-flag to `cleanDB` corresponding to singular `matU`, which makes it easier for a user to remove problem rows prior to an analysis.

I propose we also modify `longevity` and `R0` to return `NA` if `matU` is singular (and update the documentation accordingly). This would allow the user to retain rows in the `db` subset they're working with for which life expectancy or R0 cannot be calculated, which may be convenient if the user is also conducting other analyses with other sets of variables (i.e. the user doesn't have to create a bunch of different subsets of `db` for different analyses).

**Comment by jonesor** [comment]
Yes - sensible solution.
