### ISSUE TITLE
Remove 'dist == 0' check from qsdConverge

### ISSUE THREAD

**Issue by patrickbarks** [jonesor/Rage#31]
The `qsdConverge` fn checks for convergence by assessing whether `min(dist) >= conv` (where `conv` is the convergence threshold, e.g. 5%). If convergence is not reached within the allotted time, the fn returns `NA` and a warning.

The fn also returns `NA` and the same warning if `sum(dist) == 0`, which I guess indicates that the population starts out exactly at the stable distribution. This latter scenario doesn't seem like a problem to me... the fn would otherwise just return `1` if the population starts out at the stable distribution, which seems reasonable. Suggest removing this check.

**Comment by jonesor** [comment]
Agreed.
