### ISSUE TITLE
Rearrange demogstat assignment in perturbation functions

### ISSUE THREAD

**Issue by patrickbarks** [jonesor/Rage#32]
In the initial assignment of the `demogstat` variable in `matrixElementPerturbation` and `vitalRatePerturbation`, I think the `if (demogstat == "lambda")` statement should come _before_ the `if (is.character(demogstat))` statement. Otherwise the function will fail if `demogstat == 'lambda'`.

**Comment by jonesor** [comment]
OK. Makes sense.
