### ISSUE TITLE
Use human-readable matrices in documentation examples

### ISSUE THREAD

**Issue by patrickbarks** [jonesor/Rage#33]
I propose using a consistent, human-readable format when creating matrices in the `@example` section of Rage functions, e.g.

**Format 1**
```
matU <- rbind(c(  0,   0,    0,   0),
              c(0.1, 0.1,  0.1,   0),
              c(  0, 0.3,  0.3, 0.1),
              c(  0,   0,  0.2, 0.1))
```

**Format 2**
```
matU <- rbind(c(0.0, 0.0,  0.0, 0.0),
              c(0.1, 0.1,  0.1, 0.0),
              c(0.0, 0.3,  0.3, 0.1),
              c(0.0, 0.0,  0.2, 0.1))
```

I think **Format 1** is slightly easier to read in the R documentation browser. Thoughts?

**Comment by jonesor** [comment]
Good point. I find Formats super clear, but I marginally prefer Format 2.
