### ISSUE TITLE
plotLifeCycle order

### ISSUE THREAD

**Issue by jonesor** [jonesor/Rage#42]
I've copied this over from https://github.com/jonesor/compadreDB/issues/21#issue-361867590 where @RobSalGo first posted this issue.

> I think that the stages in the function plotLifeCycle get automatically re-ordered to alphabetical, unless they are given a number before them (which is not very sensible). This makes the reading of the lifecycle from left-to-right a bit less straight forward. It'd be great if we could let the authors choose the order in which the stages appear

**Comment by aornugent** [comment]
`plotLifeCycle` also throws a syntax error with any punctuation. I'm unable to assign an ordered factor so perhaps this is an issue with `dimnames`.

**Comment by jonesor** [comment]
I'm closing this now. We may remove this function from the package but for now it stays.
