### ISSUE TITLE
Should Rage have a narrower focus?

### ISSUE THREAD

**Issue by patrickbarks** [jonesor/Rage#55]
It's grown quite diverse. Many of the fns concern age-related analyses (the stated purpose), but others are not _really_ related to ageing (e.g. `perturb_` fns, `vr_` fns, `plotLifeCycle`).

Should we move some of the non-ageing fns to a separate package? I don't have a strong opinion yet, but think it's worth exploring.

As a related side note, `plotLifeCycle` has an extensive dependency chain (due to DiagrammR), that has caused some [minor CI issues](https://github.com/jonesor/Rage/pull/49#issuecomment-463616484).

**Comment by jonesor** [comment]
We discussed this at our recent workshop and the decision is to keep the existing functions even if it is a bit of a mixed bag of life history-relevant functions rather than being tightly focussed on ageing.
