### ISSUE TITLE
Add lxCrit argument to mpm_to_ functions

### ISSUE THREAD

**Issue by patrickbarks** [jonesor/Rage#57]
The `mpm_to_` fns (and `makeLifeTable`) use arguments `N`/`nSteps` to specify the number of age classes to calculate over. If a user wants to apply these to many MPMs (e.g. with COMPADRE), they'll probably just set `N` to a large constant (e.g. `1e5`). This approach can be computationally time-consuming, and is unnecessary for the many species whose lx trajectories will approach 0 long before `N`.

Therefore, suggest adding an argument `lxCrit` to these fns (default 1e-4, i.e. 1 in 10,000), and editing such that lx values are calculated until the age class reaches N OR lx drops below lxCrit — whichever occurs first.

On the 150-row Compadre subset, this change reduces the computational time on my computer from 45s to 1s (given `N = 1e5`).

If the user wants the fn to ALWAYS calculate to age class `N`, they can simply set `lxCrit = 0`.

**Comment by jonesor** [comment]
Done
