### ISSUE TITLE
Standardize argument names

### ISSUE THREAD

**Issue by patrickbarks** [jonesor/Rage#59]
Arguments 'N' (`qsd_converge`), 'nSteps' (`entropy_` fns), 'maxAge' (`longevity`), and 'xmax' (`shape_` fns), all refer to the maximum age class to which some quantity should be calculated. Suggest standardizing all to 'xmax'.

Argument 'startLife' is a bit long. Suggest shortening to 'start'.

I think the 'surv' and 'rep' arguments of the `shape_` functions could be changed to 'lx' and 'mx', respectively. Arg 'lx' is already used in the `lx_to_` functions, and could also be used in the `entropy_` functions per #58.

The remaining arguments include a mix of snake_case (e.g. 'exclude_col'), camelCase (e.g. 'reproStages'), and smushedform (e.g. 'demogstat'). Suggest standardizing, though I'm not sure how. I lean slightly toward snake_case (except for matU/matF/matC), which rOpenSci recommends for both function and argument names. But I don't feel too strongly.

Selection of current argument names:

- `vr_` fns: 'exclude_col', 'weights_col', 'surv_only_na', 'dorm_stages'
- `mpm_` fns: 'reproStages', 'matrixStages'
- various fns: 'lxCrit'
- `perturb_` fns: 'demogstat'

**Comment by jonesor** [comment]
Opened another issue #113 which will take care of this. Closing here.
