### ISSUE TITLE
entropy_k shouldn't be used with partial lx trajectories

### ISSUE THREAD

**Issue by patrickbarks** [jonesor/Rage#62]
`entropy_k` (formerly `kEntropy`) doesn't work as I'd expect with partial survivorship trajectories. For a given hazard function (declining, constant, or increasing) the value of entropy returned depends on how many age classes are used.

For example, the constant-hazard lx trajectory `0.9^(0:10)` yields an entropy of 0.434 (indicating an increasing mortality hazard) whereas the lx trajectory `0.9^(0:100)` yields an entropy of 0.998 (indicating a constant hazard). (Recall entropy < 1 indicates senescence, and entropy > 1 indicates negative senescence.)

```
x1 <- 0:10
x2 <- 0:100

# with 10 age classes, suggests positive senescence
lx1 <- 0.9^x1  # true lx trajectory has constant hazard
entropy_k(lx1, trapeze = TRUE)
> [1] 0.4341153

# with 100 age classes, suggests negligible senescence
lx2 <- 0.9^x2  # true lx trajectory has constant hazard
entropy_k(lx2, trapeze = TRUE)
> [1] 0.9978724
```
There are even cases where, for a given rate of change in the mortality hazard, using a different number of age classes qualitatively changes the interpretation regarding positive vs. negative senescence.
```
 # with 10 age classes, suggests positive senescence
hx3 <- exp(-1 - 0.2 * x1) # true hazard function is declining
lx3 <- hx_to_lx(hx3)      # survivorship
entropy_k(lx3, trapeze = TRUE)
> [1] 0.8645491

 # with 100 age classes, suggests negative senescence
hx4 <- exp(-1 - 0.2 * x2) # true hazard function is declining
lx4 <- hx_to_lx(hx4)      # survivorship
entropy_k(lx4)
> [1] 1.692954
```
At the least, I think we should include a strong warning in the documentation about this behaviour (and direct users to `shape_surv`, which does handle partial lx trajectories). On the other hand, users working with MPMs will usually be working with partial survivorship trajectories (e.g. truncated at the quasi-stable distribution), so perhaps we should just remove `entropy_k` from Rage altogether?

**Comment by jonesor** [comment]
Hi @iainmstott and @RobSalGo. Could you have a think about this issue rlated to shape/entropy. I think it's an important point, and we should at least have a warning as Patrick suggests.

**Comment by jonesor** [comment]
I will make the easiest fix, by adding a warning to the documentation as @patrickbarks  suggested in the last paragraph. Because some users have code that uses `entropy_k` I don't want to just eliminate that function alltogether (yet).

**Comment by jonesor** [comment]
This is resolved (devel branch). Closing.
