### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by jonesor** [jonesor/Rage#70]
We need a hexagonal logo for the package. The current one is a place holder based on Patrick’s one for Rcompadre. 
There should be a template available somewhere...

**Comment by jjackson-eco** [comment]
Happy to do this Owen if that helps? might be able to put my (otherwise) useless photoshop skills to the test

**Comment by jonesor** [comment]
I think @iainmstott has taken on this task. Is that right iain?

**Comment by iainmstott** [comment]
Yuss, I have some ideas at least. Whether people would like them or not is another matter

**Comment by jonesor** [comment]
@iainmstott Delivered a beautiful logo. Closing!
