### ISSUE TITLE
standard_stages could combine prop and pre-reproductive and include dormand stages. 

### ISSUE THREAD

**Issue by PolCap** [jonesor/Rage#74]
https://github.com/jonesor/Rage/blob/9d9ea415ded62257afa73e55b036d76636158b40/R/standard_stages.R#L63-L70

It was written that the function could combine propagule and pre-reproductive stages. Also, it could include dormant stages.
This requires re-writing the function.

**Comment by tdjames1** [comment]
I suggest that we remove the currently unused parameter flags (`includeProp` and `includePost`) and revise the documentation to make it a bit clearer what it does/does not do.

**Comment by jonesor** [comment]
Thanks, @tdjames1 . 
I guess we can close this now, if you and @PolCap both agree.
I don't think we should re-write the function for the upcoming release (we could add an issue to do this later though).

**Comment by tdjames1** [comment]
I agree.
