### ISSUE TITLE
allow functions with `start` argument to accept stage labels

### ISSUE THREAD

**Issue by wpetry** [jonesor/Rage#93]
This feature would allow the user to more flexibly determine the starting point for life history trait calculations by providing a stage label rather than the index number. This would potentially avoid errors by allowing the user to write more biologically-intelligible code.

```
data(mpm1)
mpm1
life_expect(mpm1$matU, start = 1)  # works
life_expect(mpm1$matU, start = "seed")  # fails
```

**Comment by jonesor** [comment]
Yes - I think this would be an excellent enhancement. Could you add it?

**Comment by wpetry** [comment]
Inventory of functions needing feature:

- [ ] `life_expect`
- [ ] `net_repro_rate`
- [ ] life table functions in `mpm_to_.R`
- [ ] `qsd_converge`
- [ ] `longevity`
- [ ] functions in `mature_.R`
- [ ] `mpm_to_table`
- [ ] `checkValidStartLife` in `utils.R`
- [ ] `entropy_d`
- [ ] `entropy_k`

We'll also need unit tests for these.

**Comment by wpetry** [comment]
Note for others that want to pitch in: I've added a helper function called `checkMatchingStageNames` to `utils.R` in 78ba2f1 that checks that row and column names for matrices with named life stages are identical.

**Comment by wpetry** [comment]
Not sure why, but #103 failed to close this issue.
